### ISSUE TITLE
[Discussion] API Documentation discussion

### ISSUE THREAD

**Issue by jd0920** [pixelprodotco/appstrap#10]
# WE HAVE AN ISSUE

There's no documentation... :stuck_out_tongue: 

Okay, I was talking with Pixel regarding ways to make documentation and he mentioned Swagger so I will be looking into that a bit more considering my noob brain it will take some time. There's also a API.md file that could be added into the repo that'll contain everything we need for documentation. Then the least wanted option would be adding JSDocs into the codebase which is time consuming. 

:+1:

**Comment by ethanm0920** [comment]
Pixel says nay to jsdoc.
