### ISSUE TITLE
Config generator doesn't generate presets folder

### ISSUE THREAD

**Issue by jd0920** [pixelprodotco/appstrap#11]
When I was initializing a demo appstrap project I was given an error on this version because presets didn't exist. Pretty easy manual fix but I think adding it into the generator would be useful. :+1:

**Comment by pixelprodotco** [comment]
@ethanm0920 i agree - would you like to make a PR for that or do you want me to put it in?

**Comment by ethanm0920** [comment]
I have it implemented just making sure it works.

**Comment by pixelprodotco** [comment]
fixed by #12
